openapi: 3.0.0
info:
  version: 1.0.0
  title: Especificacao para criacao da conta de usuário
  description: Especificacao para criacao da conta de usuário
  contact:
    email: edu.betim@yahoo.com.br
security: 
  - application:
    - read
    - write
paths:
  /accounts:
    parameters:
      - name: token
        in: header
        description: Token JWT no header
        required: true
        schema:
          type: array
          items:
            type: string
            format: string
        style: simple
        example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVC.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ
            iOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ
    get:
      summary: Recuperar todas as contas
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        400:
          description: Dados request enviados incorretos
        401:
          description: Token invalido, inexistente ou expirado
        500:
          description: erro no servidor
    post:
      summary: Cria uma nova conta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_request'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        400:
          description: Dados request enviados incorretos
        401:
          description: Token invalido, inexistente ou expirado
        500:
          description: erro no servidor
  /accounts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Id de identificação de conta de usuário
        schema:
          type: string
      - name: token
        in: header
        description: Token JWT no header
        required: true
        schema:
          type: array
          items:
            type: string
            format: string
        style: simple
        example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVC.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ
            iOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ
    get:
      summary: Recuperar uma conta de usuário pelo id
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        400:
          description: Dados request enviados incorretos
        401:
          description: Token invalido, inexistente ou expirado
        404:
          description: Recurso {id} não encontrado
        500:
          description: erro no servidor
    put:
      summary: Atualizar uma conta de usuário pelo id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_request'
      responses:
        200:
          description: Acept
        400:
          description: Dados request enviados incorretos
        401:
          description: Token invalido, inexistente ou expirado
        404:
          description: Recurso {id} não encontrado
        500:
          description: erro no servidor      
    delete:
      summary: Excluir uma conta de usuário pelo id
      responses:
        204:
          description: No content
        400:
          description: Dados request enviados incorretos
        401:
          description: Token invalido, inexistente ou expirado
        404:
          description: Recurso {id} não encontrado
        500:
          description: erro no servido
components:
  schemas:
    body_response:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - phoneNumber
        - dateBirth
        - gender
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: First
        lastName:
          type: string
          example: Last
        email:
          type: string
          format: email
          example: admin@admin.com
        phoneNumber:
          type: number
          example: 55555-5555
        dateBirth:
          type: string
          format: date
          example: 10/10/2000
        gender:
          type: string
          example: M
          enum:
            - M
            - F
    body_request:        
      type: object
      required:
        - firstName
        - lastName
        - email
        - phoneNumber
        - password
        - dateBirth
        - gender
      properties:
        firstName:
          type: string
          example: First
        lastName:
          type: string
          example: Last
        email:
          type: string
          format: email
          example: admin@admin.com
        password:
          type: string
          format: password
          example: 123
        phoneNumber:
          type: number
          example: 55555-5555
        dateBirth:
          type: string
          format: date
          example: 10/10/2000
        gender:
          type: string
          example: M
          enum:
            - M
            - F